import assert from "node:assert/strict";
import { statSync } from "node:fs";
import test from "node:test";

const PRODUCTION_CAPABILITY_SOURCE_BASELINE = [
  "app/api/http.ts",
  "app/api/intelligence/handlers.ts",
  "app/api/knowledge/handlers.ts",
  "app/api/recall/routes.ts",
  "app/api/write/handlers/create-memory-handler.ts",
  "app/cache/redis-recall-cache.ts",
  "app/code-graph.ts",
  "app/consolidation/worker.ts",
  "app/conversation/session-source-adapters.ts",
  "app/coordination/worker/worker.ts",
  "app/db/adapters/postgres-write-database.ts",
  "app/decay/production-decay.ts",
  "app/dream/dream-worker.ts",
  "app/embedding/generation-manifest.ts",
  "app/governance/memory-auto-approval-sweep.ts",
  "app/governance/memory-canary-7d-report.ts",
  "app/governance/memory-policy-engine.ts",
  "app/intelligence/graph-extraction.ts",
  "app/intelligence/llm-client.ts",
  "app/intelligence/mem0-client.ts",
  "app/knowledge/service.ts",
  "app/mcp/mcp-server.ts",
  "app/migration/recall-shadow.ts",
  "app/observability/domain-metrics.ts",
  "app/ops/auto-repair.ts",
  "app/ops/open-source-release.ts",
  "app/orchestrator/service.ts",
  "app/qdrant-sync/outbox-worker.ts",
  "app/qdrant-sync/projector.ts",
  "app/recall/model-reranker.ts",
  "app/recall/orchestrator.ts",
  "app/recall/retrievers/graph-retriever.ts",
  "app/recall/retrievers/lexical-retriever.ts",
  "app/recall/retrievers/vector-retriever.ts",
  "app/server/http-server.ts",
  "app/server/permissions.ts",
  "app/server/route-registry.ts",
  "app/skills/default-registry.ts",
  "app/write/services/create-memory-service.ts",
  "migrations/0001_initial.sql",
  "migrations/0012_knowledge_v1.sql",
  "migrations/0024_async_recovery_and_cache_invalidation.sql",
  "migrations/0029_conversation_ingest.sql",
  "migrations/0033_runtime_control_plane_observability.sql",
  "scripts/benchmark-reranker-policy.ts",
  "scripts/check-db-invariants.ts",
  "scripts/check-hardcoded-paths.ts",
  "scripts/codex-conversation-bridge.ts",
  "scripts/control-panel/routes.ts",
  "scripts/decay-run.ts",
  "scripts/embedding-calibration.ts",
  "scripts/embedding-manifest.ts",
  "scripts/generate-local-memory-embeddings.ts",
  "scripts/intelligence-quality.ts",
  "scripts/live-recall-smoke.ts",
  "scripts/memory-auto-approval.ts",
  "scripts/memory-auto-repair.ts",
  "scripts/memory-auto-update.ts",
  "scripts/memory-backup.ts",
  "scripts/memory-canary-7d-report.ts",
  "scripts/memory-code-graph.ts",
  "scripts/memory-consolidate.ts",
  "scripts/memory-control-panel.ts",
  "scripts/memory-conversation-sources.ts",
  "scripts/memory-deployment-bundle.ts",
  "scripts/memory-doctor.ts",
  "scripts/memory-governance-audit.ts",
  "scripts/memory-graph-report.ts",
  "scripts/memory-knowledge-md.ts",
  "scripts/memory-landing-scan.ts",
  "scripts/memory-migration-preflight.ts",
  "scripts/memory-mode.ts",
  "scripts/memory-platform-doctor.ts",
  "scripts/memory-policy-eval.ts",
  "scripts/memory-quality.ts",
  "scripts/memory-recall-repair.ts",
  "scripts/memory-self-improvement.ts",
  "scripts/memory-status.ts",
  "scripts/memory-trusted-agent.ts",
  "scripts/memory-xx-wrapper.ts",
  "scripts/migrate.ts",
  "scripts/open-source-export.ts",
  "scripts/open-source-preaudit.ts",
  "scripts/qdrant-reconcile.ts",
  "scripts/replay-qdrant-outbox.ts",
  "scripts/run-cache-invalidation-worker.ts",
  "scripts/run-conversation-monitor-worker.ts",
  "scripts/run-qdrant-projector-worker.ts",
  "scripts/run-write-ticket-worker.ts",
  "scripts/runtime-observability-retention.ts",
  "scripts/test-harness/layers/L4-recall-quality.ts",
  "scripts/test-harness/layers/L8-intelligence-e2e.ts",
  "scripts/test-mem0-extraction-benchmark.ts",
  "scripts/trace-replay-feedback.ts",
  "scripts/trace-retention.ts",
] as const;

function exists(path: string): boolean {
  try {
    statSync(path);
    return true;
  } catch {
    return false;
  }
}

test("public source tree retains the production capability baseline", () => {
  const missing = PRODUCTION_CAPABILITY_SOURCE_BASELINE.filter((file) => !exists(file));

  assert.deepEqual(missing, []);
});
