#!/usr/bin/env bash
#
# Start the public full/dev Docker Compose profile and verify the live wrapper.
# This script intentionally leaves the stack running for inspection.
#
set -euo pipefail

: "${MEMORY_XX_RUNTIME_PROFILE:=full}"
: "${MEMORY_XX_FASTPATH_ENABLED:=1}"
: "${MEMORY_XX_LEXICAL_SIDECAR_ENABLED:=1}"
: "${MEMORY_XX_RERANKER_UPSTREAM_ENABLED:=1}"
: "${MEMORY_XX_RERANKER_ADAPTER_ENABLED:=1}"
: "${MEMORY_XX_LLM_UPSTREAM_ENABLED:=1}"
: "${MEMORY_XX_MEM0_EXTRACTOR_ENABLED:=1}"
: "${MEMORY_XX_CONVERSATION_MONITOR_ENABLED:=1}"
: "${MEMORY_XX_CONTROL_PANEL_ENABLED:=1}"
: "${MEMORY_XX_QDRANT_PROXY_ENABLED:=1}"
: "${MEMORY_XX_MARKDOWN_PROJECTION_ENABLED:=1}"
: "${MEMORY_XX_DREAMING_ENABLED:=1}"
: "${MEMORY_XX_CACHE_INVALIDATION_WORKER_ENABLED:=1}"
: "${MEMORY_XX_WRITE_TICKET_WORKER_ENABLED:=1}"
: "${MEMORY_XX_MAINTENANCE_ENABLED:=1}"
: "${MEMORY_XX_CONSOLIDATION_ENABLED:=1}"
: "${MEMORY_XX_RUNTIME_ISSUE_DETECTION_ENABLED:=1}"
: "${MEMORY_XX_AUTO_REPAIR_ENABLED:=1}"
: "${MEMORY_XX_REPAIR_REPORT_ENABLED:=1}"
: "${MEMORY_XX_LANDING_SCAN_ENABLED:=1}"
: "${MEMORY_XX_CANARY_7D_REPORT_ENABLED:=1}"
: "${MEMORY_XX_QUALITY_RUNNER_ENABLED:=1}"
: "${MEMORY_XX_GOVERNANCE_REPORT_ENABLED:=1}"

: "${MEMORY_XX_RERANKER_UPSTREAM_HEALTH_URL:=http://memory-xx-dev-reranker-upstream:8084/health}"
: "${MEMORY_XX_RERANKER_DOWNSTREAM_URL:=http://memory-xx-dev-reranker-upstream:8084/v3/rerank}"
: "${MEMORY_XX_RERANKER_DOWNSTREAM_MODELS_URL:=http://memory-xx-dev-reranker-upstream:8084/v3/models}"
: "${MEMORY_XX_LLM_UPSTREAM_HEALTH_URL:=http://memory-xx-dev-chat-upstream:5223/health}"
: "${MEMORY_INTELLIGENCE_BASE_URL:=http://memory-xx-dev-chat-upstream:5223/v1}"

: "${MEMORY_XX_WRAPPER_HOST_PORT:=15100}"
: "${MEMORY_XX_EMBEDDING_PROXY_HOST_PORT:=15221}"
: "${MEMORY_XX_DEV_EMBEDDING_HOST_PORT:=15222}"
: "${MEMORY_XX_DEV_CHAT_HOST_PORT:=15223}"
: "${MEMORY_XX_POSTGRES_HOST_PORT:=15432}"
: "${MEMORY_XX_REDIS_HOST_PORT:=16379}"
: "${MEMORY_XX_QDRANT_HOST_PORT:=16333}"
: "${MEMORY_XX_QDRANT_PROXY_HOST_PORT:=16334}"
: "${MEMORY_XX_CONTROL_PANEL_HOST_PORT:=15310}"
: "${MEMORY_XX_FASTPATH_HOST_PORT:=15200}"
: "${MEMORY_XX_LEXICAL_HOST_PORT:=15210}"
: "${MEMORY_XX_MEM0_EXTRACTOR_HOST_PORT:=15220}"
: "${MEMORY_XX_DEV_RERANKER_HOST_PORT:=18084}"
: "${MEMORY_XX_RERANKER_ADAPTER_HOST_PORT:=18085}"
: "${MEMORY_XX_COMPOSE_FULL_WAIT_MS:=90000}"
: "${MEMORY_XX_COMPOSE_FULL_SKIP_FUNCTIONAL:=0}"
: "${MEMORY_XX_COMPOSE_FULL_BUILD:=1}"

export MEMORY_XX_RUNTIME_PROFILE
export MEMORY_XX_FASTPATH_ENABLED
export MEMORY_XX_LEXICAL_SIDECAR_ENABLED
export MEMORY_XX_RERANKER_UPSTREAM_ENABLED
export MEMORY_XX_RERANKER_ADAPTER_ENABLED
export MEMORY_XX_LLM_UPSTREAM_ENABLED
export MEMORY_XX_MEM0_EXTRACTOR_ENABLED
export MEMORY_XX_CONVERSATION_MONITOR_ENABLED
export MEMORY_XX_CONTROL_PANEL_ENABLED
export MEMORY_XX_QDRANT_PROXY_ENABLED
export MEMORY_XX_MARKDOWN_PROJECTION_ENABLED
export MEMORY_XX_DREAMING_ENABLED
export MEMORY_XX_CACHE_INVALIDATION_WORKER_ENABLED
export MEMORY_XX_WRITE_TICKET_WORKER_ENABLED
export MEMORY_XX_MAINTENANCE_ENABLED
export MEMORY_XX_CONSOLIDATION_ENABLED
export MEMORY_XX_RUNTIME_ISSUE_DETECTION_ENABLED
export MEMORY_XX_AUTO_REPAIR_ENABLED
export MEMORY_XX_REPAIR_REPORT_ENABLED
export MEMORY_XX_LANDING_SCAN_ENABLED
export MEMORY_XX_CANARY_7D_REPORT_ENABLED
export MEMORY_XX_QUALITY_RUNNER_ENABLED
export MEMORY_XX_GOVERNANCE_REPORT_ENABLED
export MEMORY_XX_RERANKER_UPSTREAM_HEALTH_URL
export MEMORY_XX_RERANKER_DOWNSTREAM_URL
export MEMORY_XX_RERANKER_DOWNSTREAM_MODELS_URL
export MEMORY_XX_LLM_UPSTREAM_HEALTH_URL
export MEMORY_INTELLIGENCE_BASE_URL
export MEMORY_XX_WRAPPER_HOST_PORT
export MEMORY_XX_EMBEDDING_PROXY_HOST_PORT
export MEMORY_XX_DEV_EMBEDDING_HOST_PORT
export MEMORY_XX_DEV_CHAT_HOST_PORT
export MEMORY_XX_POSTGRES_HOST_PORT
export MEMORY_XX_REDIS_HOST_PORT
export MEMORY_XX_QDRANT_HOST_PORT
export MEMORY_XX_QDRANT_PROXY_HOST_PORT
export MEMORY_XX_CONTROL_PANEL_HOST_PORT
export MEMORY_XX_FASTPATH_HOST_PORT
export MEMORY_XX_LEXICAL_HOST_PORT
export MEMORY_XX_MEM0_EXTRACTOR_HOST_PORT
export MEMORY_XX_DEV_RERANKER_HOST_PORT
export MEMORY_XX_RERANKER_ADAPTER_HOST_PORT

if [[ "$MEMORY_XX_COMPOSE_FULL_BUILD" == "1" ]]; then
  docker compose --profile full --profile dev up -d --remove-orphans --build
else
  docker compose --profile full --profile dev up -d --remove-orphans
fi

ADMIN_TOKEN="$(
  docker compose exec -T memory-xx sh -lc 'printf "%s" "$MEMORY_XX_ADMIN_TOKEN"'
)"
ADMIN_ENV=("MEMORY_XX_ADMIN_TOKEN=$ADMIN_TOKEN")
FUNCTIONAL_AUTH_ENV=(
  "MEMORY_XX_API_TOKEN=$ADMIN_TOKEN"
  "MEMORY_XX_ADMIN_TOKEN=$ADMIN_TOKEN"
)

env "${ADMIN_ENV[@]}" TMPDIR="${TMPDIR:-/tmp}" \
  npm run smoke:compose-profile-live -- \
    --url "http://127.0.0.1:${MEMORY_XX_WRAPPER_HOST_PORT}/health" \
    --wait-ms "$MEMORY_XX_COMPOSE_FULL_WAIT_MS"

if [[ "$MEMORY_XX_COMPOSE_FULL_SKIP_FUNCTIONAL" == "1" ]]; then
  echo "Skipping functional smoke because MEMORY_XX_COMPOSE_FULL_SKIP_FUNCTIONAL=1"
  exit 0
fi

env \
  WRAPPER="http://127.0.0.1:${MEMORY_XX_WRAPPER_HOST_PORT}" \
  PG_DB="postgres://postgres:postgres@127.0.0.1:${MEMORY_XX_POSTGRES_HOST_PORT}/memory_xx" \
  QDRANT_BASE="http://127.0.0.1:${MEMORY_XX_QDRANT_HOST_PORT}" \
  QDRANT_COLLECTION="${MEMORY_XX_QDRANT_COLLECTION:-memory-xx}" \
  "${FUNCTIONAL_AUTH_ENV[@]}" \
  TMPDIR="${TMPDIR:-/tmp}" \
  npm run smoke:functional -- m1
