#!/usr/bin/env bash
#
# Start the public enhanced/dev Docker Compose profile and verify pluggable sidecars.
# This script intentionally leaves the stack running for inspection.
#
set -euo pipefail

: "${MEMORY_XX_RUNTIME_PROFILE:=enhanced}"
: "${MEMORY_XX_FASTPATH_ENABLED:=1}"
: "${MEMORY_XX_LEXICAL_SIDECAR_ENABLED:=1}"
: "${MEMORY_XX_RERANKER_UPSTREAM_ENABLED:=1}"
: "${MEMORY_XX_RERANKER_ADAPTER_ENABLED:=1}"
: "${MEMORY_XX_LLM_UPSTREAM_ENABLED:=1}"
: "${MEMORY_XX_MEM0_EXTRACTOR_ENABLED:=1}"
: "${MEMORY_XX_CONVERSATION_MONITOR_ENABLED:=1}"
: "${MEMORY_XX_CONTROL_PANEL_ENABLED:=1}"
: "${MEMORY_XX_QDRANT_PROXY_ENABLED:=1}"

: "${MEMORY_XX_RERANKER_UPSTREAM_HEALTH_URL:=http://memory-xx-dev-reranker-upstream:8084/health}"
: "${MEMORY_XX_RERANKER_DOWNSTREAM_URL:=http://memory-xx-dev-reranker-upstream:8084/v3/rerank}"
: "${MEMORY_XX_RERANKER_DOWNSTREAM_MODELS_URL:=http://memory-xx-dev-reranker-upstream:8084/v3/models}"
: "${MEMORY_XX_LLM_UPSTREAM_HEALTH_URL:=http://memory-xx-dev-chat-upstream:5223/health}"
: "${MEMORY_INTELLIGENCE_BASE_URL:=http://memory-xx-dev-chat-upstream:5223/v1}"

: "${MEMORY_XX_WRAPPER_HOST_PORT:=14100}"
: "${MEMORY_XX_EMBEDDING_PROXY_HOST_PORT:=14221}"
: "${MEMORY_XX_DEV_EMBEDDING_HOST_PORT:=14222}"
: "${MEMORY_XX_DEV_CHAT_HOST_PORT:=14223}"
: "${MEMORY_XX_POSTGRES_HOST_PORT:=14432}"
: "${MEMORY_XX_REDIS_HOST_PORT:=14379}"
: "${MEMORY_XX_QDRANT_HOST_PORT:=14333}"
: "${MEMORY_XX_QDRANT_PROXY_HOST_PORT:=14334}"
: "${MEMORY_XX_CONTROL_PANEL_HOST_PORT:=14310}"
: "${MEMORY_XX_FASTPATH_HOST_PORT:=14200}"
: "${MEMORY_XX_LEXICAL_HOST_PORT:=14210}"
: "${MEMORY_XX_MEM0_EXTRACTOR_HOST_PORT:=14220}"
: "${MEMORY_XX_DEV_RERANKER_HOST_PORT:=14084}"
: "${MEMORY_XX_RERANKER_ADAPTER_HOST_PORT:=14085}"
: "${MEMORY_XX_COMPOSE_ENHANCED_WAIT_MS:=90000}"
: "${MEMORY_XX_COMPOSE_ENHANCED_BUILD:=1}"

export MEMORY_XX_RUNTIME_PROFILE
export MEMORY_XX_FASTPATH_ENABLED
export MEMORY_XX_LEXICAL_SIDECAR_ENABLED
export MEMORY_XX_RERANKER_UPSTREAM_ENABLED
export MEMORY_XX_RERANKER_ADAPTER_ENABLED
export MEMORY_XX_LLM_UPSTREAM_ENABLED
export MEMORY_XX_MEM0_EXTRACTOR_ENABLED
export MEMORY_XX_CONVERSATION_MONITOR_ENABLED
export MEMORY_XX_CONTROL_PANEL_ENABLED
export MEMORY_XX_QDRANT_PROXY_ENABLED
export MEMORY_XX_RERANKER_UPSTREAM_HEALTH_URL
export MEMORY_XX_RERANKER_DOWNSTREAM_URL
export MEMORY_XX_RERANKER_DOWNSTREAM_MODELS_URL
export MEMORY_XX_LLM_UPSTREAM_HEALTH_URL
export MEMORY_INTELLIGENCE_BASE_URL
export MEMORY_XX_WRAPPER_HOST_PORT
export MEMORY_XX_EMBEDDING_PROXY_HOST_PORT
export MEMORY_XX_DEV_EMBEDDING_HOST_PORT
export MEMORY_XX_DEV_CHAT_HOST_PORT
export MEMORY_XX_POSTGRES_HOST_PORT
export MEMORY_XX_REDIS_HOST_PORT
export MEMORY_XX_QDRANT_HOST_PORT
export MEMORY_XX_QDRANT_PROXY_HOST_PORT
export MEMORY_XX_CONTROL_PANEL_HOST_PORT
export MEMORY_XX_FASTPATH_HOST_PORT
export MEMORY_XX_LEXICAL_HOST_PORT
export MEMORY_XX_MEM0_EXTRACTOR_HOST_PORT
export MEMORY_XX_DEV_RERANKER_HOST_PORT
export MEMORY_XX_RERANKER_ADAPTER_HOST_PORT

if [[ "$MEMORY_XX_COMPOSE_ENHANCED_BUILD" == "1" ]]; then
  docker compose --profile enhanced --profile dev up -d --remove-orphans --build
else
  docker compose --profile enhanced --profile dev up -d --remove-orphans
fi

ADMIN_TOKEN="$(
  docker compose exec -T memory-xx sh -lc 'printf "%s" "$MEMORY_XX_ADMIN_TOKEN"'
)"
ADMIN_ENV=("MEMORY_XX_ADMIN_TOKEN=$ADMIN_TOKEN")

env "${ADMIN_ENV[@]}" TMPDIR="${TMPDIR:-/tmp}" \
  npm run smoke:compose-profile-live -- \
    --url "http://127.0.0.1:${MEMORY_XX_WRAPPER_HOST_PORT}/health" \
    --wait-ms "$MEMORY_XX_COMPOSE_ENHANCED_WAIT_MS"
